version: '3.8'

services:
  ipfs-node:
    image: ipfs/go-ipfs:latest
    container_name: swarm-storage-ipfs
    restart: unless-stopped
    ports:
      - "4001:4001" # Swarm port
      - "4001:4001/udp" # Swarm port (QUIC)
      - "5001:5001" # API port
      - "8080:8080" # Gateway port
    volumes:
      - ipfs_data:/data/ipfs
      - ./swarm.key:/data/ipfs/swarm.key:ro
    environment:
      IPFS_PROFILE: server
      IPFS_ROUTING_TYPE: dht
      IPFS_AUTOTLS_ENABLED: "false"
    command: daemon --migrate=true --enable-pubsub-experiment

volumes:
  ipfs_data:
